version: 0.2

phases:
  pre_build:
    commands:
      # Create a variable containing the first 8 chars of the commit id
      - COMMIT_ID=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}
      - echo "Build ${COMMIT_ID}"
      - printf '{"BuildId":"%s"}' "${COMMIT_ID}" > /tmp/buildData.json

      # CD into the backend and create the directory to be exported
      - cd backend
      - mkdir dist
      - mkdir dist/build-${COMMIT_ID}
      - mkdir dist/build-${COMMIT_ID}/lambda
  build:
    commands:
      # Copy the backend template used for manual approval
      - cp template.yml dist/build-${COMMIT_ID}

      # Zip code for lambdas
      - zip -r -j dist/build-${COMMIT_ID}/lambda/main.zip lambda/main/
artifacts:
  secondary-artifacts:
    BackendBuild:
      base-directory: backend/dist
      files:
        - "**/*"
    BuildData:
      files: /tmp/buildData.json
      discard-paths: yes
