version: 0.2

phases:
  pre_build:
    commands:
      - cd backend
      - mkdir dist
      - mkdir dist/lambda
  build:
    commands:
      - zip -r -j dist/lambda/main.zip lambda/main/
artifacts:
  files:
    - "**/*"
  base-directory: backend/dist
